spring:
  cloud:
    stream:
      bindings:
        input:
          destination: opal-confirm-service
          group: clean-data
        output:
          destination: clean-data
      rabbit:
        bindings:
          output:
            producer:
              exchangeDurable: false
          input:
            consumer:
              exchangeDurable: true
              durableSubscription: false

  rabbitmq:
    host: ${RABBITMQ_ADDRESS}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
server:
  port: ${PORT:8006}


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}