
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: clean-data
          group: civet
        output:
          destination: civet
      rabbit:
        bindings:
          output:
            producer:
              exchangeDurable: false
          input:
            consumer:
              exchangeDurable: false      
              durableSubscription: false
  rabbitmq:
    host: ${RABBITMQ_ADDRESS}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
server:
  port: ${PORT:8003}
  
